### ISSUE TITLE
General TODO list

### ISSUE THREAD

**Issue by husisy** [numqi/numqi#1]
(this might be not a good issue, i am just testing how to use github/issue)

- [ ] Semantic Versioning [semver-link](https://semver.org/), other option, calendar versioning [calver-link](https://calver.org/), personally, I prefer semver
- [ ] upload to pypi, add github/action
- [ ] add conda-forge package, add github/action
- [ ] add more explanation to those `docs/*.ipynb` with code only
- [ ] move `docs/misc.md/TOOD` here
